=== nplforcr/NLP/ACE05Navigator/ace05/dtd/ag-1.1.dtd
<!-- 

A DTD for Annotation Graphs (ATLAS Level 0), derived from the AIF DTD.

2000-10-26   v1.0b1  Steven Bird (LDC)
2000-11-08   v1.0b2  Steven Bird (LDC)
2000-11-21   v1.0b3  Steven Bird (LDC)
2001-01-30   v1.0    Steven Bird (LDC)
2001-04-02   v1.1b1  Steven Bird (LDC)
2001-04-23   v1.1b2  Steven Bird (LDC)
2001-09-15   v1.1b3  Steven Bird (LDC)
2001-12-20   v1.1    Steven Bird (LDC)

-->

<!-- Overview:

            AGSet  := Metadata Timeline* AG*
                   [attrs: id, version, xmlns, xmlns:xlink]

          Metadata := ANY

                AG := Metadata? Anchor* Annotation*
                   [attrs: id, type, timeline?]

          Timeline := Metadata? Signal*
            Signal := Metadata?
                   [attrs: id, mimeClass, mimeType, encoding,
                    xlink:type, xlink:href, track?]

            Anchor := EMPTY
                   [attrs: id, offset?, unit?, signals?]

        Annotation := Feature*
                   [attrs: id, type, start, end]
           Feature := PCDATA
                   [attrs: name]
-->

<!ELEMENT Metadata ( MetadataElement* )>

<!ELEMENT MetadataElement ANY>
<!ATTLIST MetadataElement
    name        CDATA  #REQUIRED
>

<!ELEMENT AGSet
  ( Metadata, Timeline*, AG* )>
<!ATTLIST AGSet
    id          ID     #REQUIRED
    version     CDATA  #FIXED    "1.0"
    xmlns       CDATA  #FIXED    "http://www.ldc.upenn.edu/atlas/ag/"
    xmlns:xlink CDATA  #FIXED    "http://www.w3.org/1999/xlink"
    xmlns:dc    CDATA  #FIXED    "http://purl.org/DC/documents/rec-dces-19990702.htm"
>

<!ELEMENT AG
  ( Metadata?, Anchor*, Annotation* )>
<!ATTLIST AG
    id          ID         #REQUIRED
    type        NMTOKEN    #IMPLIED
    timeline    IDREF      #IMPLIED
>

<!ELEMENT Timeline
  ( Metadata?, Signal* )>
<!ATTLIST Timeline
    id          ID         #REQUIRED
>

<!ELEMENT Signal ( Metadata? )>
<!ATTLIST Signal
    id          ID         #REQUIRED
    mimeClass   CDATA      #REQUIRED
    mimeType    CDATA      #REQUIRED
    encoding    CDATA      #REQUIRED
    unit        CDATA      #REQUIRED
    xlink:type  CDATA      #FIXED        "simple"
    xlink:href  CDATA      #REQUIRED
    track       NMTOKEN    #IMPLIED
>

<!ELEMENT Annotation ( Feature* )>
<!ATTLIST Annotation
    id         ID          #REQUIRED
    type       NMTOKEN     #REQUIRED
    start      IDREF       #REQUIRED
    end        IDREF       #REQUIRED
>

<!ELEMENT Feature (#PCDATA)>
<!ATTLIST Feature
    name        NMTOKEN    #REQUIRED
>

<!--
  Note that feature content may be structured, and the recommended
  way is to use Dublin Core Structured Values DCSV (Cox & Iannella)
  http://purl.org/dc/documents/rec/dcmi-dcsv-20000728.htm
  e.g. "name.given=Eric; name.family=Van Sandt; height=170 cm"
-->

<!ELEMENT Anchor EMPTY>
<!ATTLIST Anchor
    id          ID         #REQUIRED
    offset      CDATA      #IMPLIED
    unit        CDATA      #IMPLIED
    signals     IDREFS     #IMPLIED
>

=== nplforcr/NLP/ACE05Navigator/ace05/data/English/bn/timex2norm/CNN_ENG_20030607_173310.4.ag.xml
<?xml version="1.0"?>
<!DOCTYPE AGSet SYSTEM "ag-1.1.dtd">
<AGSet id="CNN_ENG_20030607_173310.4" version="1.0" xmlns="http://www.ldc.upenn.edu/atlas/ag/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/DC/documents/rec-dces-19990702.htm">
<Metadata>
<MetadataElement name="author">LDC</MetadataElement>
<MetadataElement name="encoding">UTF-8</MetadataElement>
<MetadataElement name="source"></MetadataElement>
<MetadataElement name="type">text</MetadataElement>
<MetadataElement name="uri">CNN_ENG_20030607_173310.4.sgm</MetadataElement>
<MetadataElement name="version">3.1</MetadataElement>
</Metadata>
<Timeline id="CNN_ENG_20030607_173310.4:T1">
<Signal id="CNN_ENG_20030607_173310.4:T1:1" mimeClass="text" mimeType="NULL" encoding="unknown" unit="char" xlink:type="simple" xlink:href="URI" track="NULL"></Signal>
</Timeline>
<AG id="CNN_ENG_20030607_173310.4:1" timeline="CNN_ENG_20030607_173310.4:T1">
<Metadata>
<MetadataElement name="docid">CNN_ENG_20030607_173310.4</MetadataElement>
</Metadata>
<Anchor id="CNN_ENG_20030607_173310.4:1:8e" offset="116.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:8f" offset="134.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:3O" offset="169.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:3P" offset="171.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:9" offset="237.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:B" offset="237.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:A" offset="240.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:C" offset="240.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:8i" offset="314.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:8j" offset="322.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:K" offset="388.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:M" offset="388.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:L" offset="400.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:N" offset="400.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:O" offset="403.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Q" offset="403.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:P" offset="404.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:R" offset="404.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:S" offset="417.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:V" offset="417.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:U" offset="418.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:W" offset="418.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:DS" offset="447.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:X" offset="447.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Z" offset="449.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:a" offset="454.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:f" offset="456.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:h" offset="456.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:g" offset="458.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:i" offset="458.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:j" offset="466.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:l" offset="466.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:DU" offset="468.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Y" offset="468.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:k" offset="468.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:m" offset="468.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:n" offset="486.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:p" offset="486.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:o" offset="489.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:q" offset="489.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:8m" offset="515.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:8n" offset="523.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:11" offset="526.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:r" offset="526.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:z" offset="526.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:t" offset="527.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:u" offset="527.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:10" offset="540.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:12" offset="540.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:13" offset="543.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:19" offset="543.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1B" offset="543.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1D" offset="543.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1K" offset="543.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:91" offset="543.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1A" offset="546.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1C" offset="546.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:15" offset="560.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:16" offset="566.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1M" offset="569.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1N" offset="572.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1G" offset="583.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:14" offset="588.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1F" offset="588.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1H" offset="588.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1L" offset="588.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:92" offset="588.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:s" offset="588.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1Q" offset="604.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1S" offset="608.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1R" offset="612.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1U" offset="612.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1Z" offset="619.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1b" offset="619.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1a" offset="621.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1c" offset="621.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1h" offset="674.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1j" offset="689.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1i" offset="692.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1k" offset="692.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1d" offset="706.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1f" offset="706.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1e" offset="707.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1g" offset="707.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1l" offset="765.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1n" offset="765.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1m" offset="770.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1o" offset="770.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:8q" offset="817.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:8r" offset="826.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1p" offset="829.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1r" offset="829.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1q" offset="832.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1s" offset="832.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1t" offset="872.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1x" offset="872.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1z" offset="872.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:99" offset="872.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1y" offset="874.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:20" offset="874.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1v" offset="876.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1u" offset="879.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1w" offset="879.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:9A" offset="879.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:21" offset="897.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:23" offset="897.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:22" offset="902.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:24" offset="902.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Db" offset="941.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Dj" offset="941.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Cn" offset="946.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Cp" offset="946.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Co" offset="948.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:Cq" offset="948.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:1" offset="956.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:3" offset="956.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:2" offset="960.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:4" offset="960.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:29" offset="966.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:2B" offset="966.000000"></Anchor>
<Anchor id="CNN_ENG_20030607_173310.4:1:2A" offset="971.000000"></Anchor>
